name: Build & Publish (Forge)

on:
  push:
    tags:
      - "v*" # normal release path: push a version tag like v1.2.3
  workflow_dispatch:
    inputs:
      tag:
        description: ""
        required: false
        default: ""

permissions:
  contents: write

env:
  # Build a tag name: user input → or the pushed tag → or an auto test tag
  RELEASE_TAG: ${{ github.event.inputs.tag != '' && github.event.inputs.tag || (startsWith(github.ref, 'refs/tags/') && github.ref_name) || format('test-v{0}', github.run_number) }}

jobs:
  mac:
    runs-on: macos-latest
    env:
      NODE_VERSION: "20"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci
      - run: npm run make -- --platform=darwin
      # - run: npm run make -- --platform=darwin --arch=arm64
      # - run: npm run make -- --platform=darwin --arch=x64

      - name: Upload mac artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mac
          path: |
            out/make/dmg/darwin/**/*
            out/make/zip/darwin/**/*

  windows:
    runs-on: windows-latest
    env:
      NODE_VERSION: "20"
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - run: npm ci
      # optional 64-bit:
      # - run: npm run make -- --platform=win32 --arch=x64
      # optional 32-bit:
      - run: npm run make -- --platform=win32 --arch=ia32

      - name: Upload win artifacts
        uses: actions/upload-artifact@v4
        with:
          name: win
          path: |
            out/make/squirrel.windows/**/*

  release:
    name: Create GitHub Release with all artifacts
    runs-on: ubuntu-latest
    needs: [mac, windows]
    steps:
      - name: Download mac artifacts
        uses: actions/download-artifact@v4
        with:
          name: mac
          path: dist/mac

      - name: Download win artifacts
        uses: actions/download-artifact@v4
        with:
          name: win
          path: dist/win

      - name: Publish GitHub Release (draft for manual runs)
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ env.RELEASE_TAG }}
          tag_name: ${{ env.RELEASE_TAG }}
          # If this run was triggered via workflow_dispatch (manual), keep it a draft.
          draft: ${{ github.event_name == 'workflow_dispatch' }}
          prerelease: false
          files: |
            dist/mac/**/*
            dist/win/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
